import type { ChallengeData, TrackerState } from "@/lib/tracker";
import { allChallengeDates, formatDate, isFutureChallengeDate, scoreForDate } from "@/lib/tracker";
import { LockKeyhole } from "lucide-react";

export function ContributionCalendar({ state, onSelect, selectedDate }: { state: TrackerState; onSelect?: (key: string) => void; selectedDate?: string }) {
  const challenge = state.challenge as ChallengeData;
  const dates = allChallengeDates(challenge);
  return <div className="surface p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Your 90-day record</p><h2 className="mt-1 panel-title">Consistency calendar</h2></div><div className="flex items-center gap-2 text-[10px] text-white/35" aria-label="Calendar intensity legend from less to more complete"><span>Less</span>{[0, 1, 2, 3].map(score => <i key={score} aria-hidden="true" className={`size-3 rounded-[4px] ${score === 0 ? "bg-white/[.06]" : score === 1 ? "bg-[#809b37]" : score === 2 ? "bg-[#a8c744]" : "bg-[#d9ff3e]"}`} />)}<span>More</span></div></div><div className="grid grid-cols-10 gap-1.5 sm:grid-cols-[repeat(15,minmax(0,1fr))]" aria-label="90-day progress calendar">{dates.map((date, index) => { const key = date.toISOString().slice(0, 10); const future = isFutureChallengeDate(challenge, key); const score = scoreForDate(state, key); const colour = future ? "bg-white/[.025] text-white/20" : score === 0 ? "bg-white/[.06] text-white/35 hover:bg-white/[.12]" : score === 1 ? "bg-[#809b37] text-[#0b0d12]" : score === 2 ? "bg-[#a8c744] text-[#0b0d12]" : "bg-[#d9ff3e] text-[#0b0d12]"; const label = `Day ${index + 1}, ${formatDate(date, { weekday: "long", month: "long", day: "numeric" })}, ${future ? "future day locked" : `${score} of 3 complete`}`; return <button key={key} onClick={() => !future && onSelect?.(key)} title={label} aria-label={label} aria-current={selectedDate === key ? "date" : undefined} className={`relative aspect-square rounded-[5px] text-[9px] font-semibold transition-transform hover:-translate-y-0.5 ${colour} ${selectedDate === key ? "ring-2 ring-[#8291ff] ring-offset-2 ring-offset-[#11151f]" : ""}`} disabled={future}>{future ? <LockKeyhole aria-hidden="true" className="mx-auto size-2.5" /> : index + 1}</button>; })}</div></div>;
}
